# fly.toml app configuration file for the chungus-battles-frontend DEV environment
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chungus-battles-frontend-dev'
primary_region = 'waw'

[build]
  [build.args]
    BUILD_CONFIGURATION = 'staging'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
