name: Deploy Frontend to GH Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.0
      - name: Adding Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 22

      - name: Set up repository
        run: |
          git config --global user.email "arkheonos@gmail.com"
          git config --global user.name "arongida"
          git remote add undefined https://github.com/arongida/chungus-battles-frontend.git
          git push -u undefined main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Prepare and deploy
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npm run ng deploy --base-href=/chungus-battles-frontend/ --name="arongida" --email="arkheonos@gmail.com"
