name: Deploy Frontend to GH Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Adding Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to gh pages
        run: npx angular-cli-ghpages --dir=dist/chungus-battles-frontend
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
